### ISSUE TITLE
Updates to wsclean

### ISSUE THREAD

**Issue by AlecThomson** [pkgw/conda-recipes#13]
Hi @pkgw - thanks very much for maintaining these recipes!

I'm wondering if it'd be possible to update the `wslcean` recipes to:
a) Point to the new repo location on [gitlab](https://gitlab.com/aroffringa/wsclean)
b) Support newer versions - the latest stable release is v3.1

Thanks again!

**Comment by pkgw** [comment]
Thanks for asking! I don't maintain these recipes as well as I used to, but I did just push a wsclean 3.1 package for linux-64 to the `pkgw-forge` channel. I got an osx-64 package to build, but it looks like it doesn't want to run because conda-forge's openblas is MPI-enabled. I'm not sure how much of a hassle it would be to work around that.
