### ISSUE TITLE
Disable "MSMetaData::_computeScanAndSubScanProperties" Log Info

### ISSUE THREAD

**Issue by Gravi80** [pkgw/conda-recipes#6]
Calling any methods on MSMetaData prints INFO log along with the return value.

```
import casac
csc=casac.casac
ms = csc.ms()
ms.open('your.ms')
md=ms.metadata()
md.scannumbers()
```
> 2017-09-27 06:07:47	INFO	MSMetaData::_computeScanAndSubScanProperties 	Computing scan and subscan properties...
> array([1, 2, 3, 4, 5, 6, 7], dtype=int32)

Is there a way to disable these INFO logs ?

**Comment by pkgw** [comment]
It is surprisingly tedious to do so. My toolkit of Python utilities includes a function that helps achieve this, [pwkit.environments.casa.logger()](http://pwkit.readthedocs.io/en/latest/environments/casa/utilities/#pwkit.environments.casa.util.logger). You can see how it's implemented [here](https://github.com/pkgw/pwkit/blob/master/pwkit/environments/casa/util.py#L176).

I'm closing this issue since I think this answer should meet your needs, but feel free to continue the discussion if needed.

**Comment by Gravi80** [comment]
Thanks for your suggestion Peter, pwkit works 👍

**Comment by Gravi80** [comment]
After reading the source code of pwkit logger, figured out that the same can be achieved by casac module itself :
```
import casac
csc=casac.casac
casalog=csc.logsink()
casalog.showconsole(True)
casalog.setglobal(True)
casalog.filter('WARN')
ms = csc.ms()
ms.open('your.ms')
md=ms.metadata()
md.scannumbers()
```
> [1 2 3 4 5 6 7]

**Comment by pkgw** [comment]
Yes, I think the only difference will be that without the extra magic in pwkit, a program that sets the CASA logger manually will always create a file called "casapy.log" in the current directory. Perhaps they have changed the behavior so that it stops doing that, though.
